name: Run Selenium Scraper

on:
  schedule:
    - cron: "0 2 * * *"  # Runs at 2 AM UTC (modify if needed)
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Scraper
        run: python scraper.py  # Change "scraper.py" to your actual script filename

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: scraped-data
          path: aave_posts_complete.csv  # Adjust to match your output file
