name: Run Web Scraper

on:
  schedule:
    - cron: "0 21 * * *"  # Runs at 2 AM Pakistan Time (9 PM UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Ensures script runs for up to 6 hours

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py  # Change to your script's filename

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Updated scraped data $(date -u +"%Y-%m-%d %H:%M:%S")"
            git push
          fi
